### PR TITLE
Fix to honor disableShowClear option

### PR DESCRIPTION
**Pull request by vidhill**
Hello, 

I discovered that the disableShowClear options appears to not be working,  
rather than create an issue I created a pull request. 

Hope this is okay, 
thanks,
vidhill

### CODE REVIEW

**Comment by jhuesos** [comment]
Can you please add a few tests to make sure the disableShowClear is never broken again? In addition, can you update CHANGELOG.md with your fix? Thanks

**Comment by vidhill** [comment]
Okay, I will do that

**Comment by vidhill** [comment]
I have added tests for disableShowClear behaviour, and updated the Changelog

**Comment by vidhill** [comment]
Anything I can do to help get this through?

**Review by jhuesos — APPROVED** [review]
Cool. Thanks for your help. And I am sorry but this week it has been the busiest week of the year almost.

Merging this PR now.

**Comment by jhuesos** [comment]
Released version **2.1.5** with your fix. Thanks again for the help

**Pull request merged**
