### PR TITLE
Some modifications of mine

### PR DESCRIPTION
**Pull request by tanithdalban**
I had to do those modifications to adapte the component in my project.
I put them here, if it usefull.

Note : i force the always-float-label in the composant (due to design in my project)

### CODE REVIEW

**Comment by tachyon1337** [comment]
I'll take a look at the pull request. On a cursory examination I did note you changed the event delimiter/name spacing from dot to dash. I'm going to keep the default as dot but enable modification to this declaratively using a public property because of this issue

https://github.com/ellipticaljs/paper-autocomplete/issues/9#issuecomment-226946152

although I think I go with event-delimiter as the prop name.

**Comment by tanithdalban** [comment]
This pull request is not a very "request", it was the simpiest way for me to show differences i made in the project. 

I had to change the event naming because of :

listeners: {
'myinput.autocomplete.change':'_myInputChange'
}

Event goes wrong...because of the dot.

**Comment by tachyon1337** [comment]
"Take a look at the pull request" simply means I'll look it over as a candidate for merging with this repo. Your pull request doesn't fix a current bug. It looks like it adds additional functionality. I will have to test that. If I do merge, I will back out the hard-coded "dash" in the events, instead going with a configurable public property that can be declaratively set in a tag attribute.

**Comment by tachyon1337** [comment]
Manually merged floating label behavior by default.

**Pull request closed without merging**
