### PR TITLE
Integrating demo in master following Polymer standard convention

### PR DESCRIPTION
**Pull request by jhuesos**
I have move the content of the demo from the `gh-pages` branch into a new html file in the demo page. So now when you serve the component with `polymer serve` you will see the DEMO link and you will see examples.

I tried to maintain as close as possible the content from (http://ellipticaljs.github.io/paper-autocomplete/), even trying to maintain the styles.

There is a few things that need to be done: the examples page contains more documentation: there is no information about events, methods, etc. I am planning to continue working on that, but I would prefer to get some feedback first. Kind of know if maintainers of the project agree with this change before I waste more time.

As a plus, I also added `.editorconfig` that I hope you don't mind. It is very useful for people like me who worked in different projects all the time.

### CODE REVIEW

**Comment by tachyon1337** [comment]
> I have to use the github path because css-docs is not available in the bower repository.

@jhuesos 

Hmmm, apparently, I neglected to actually register that repo w/ bower. I just registered it.

**Comment by tachyon1337** [comment]
> I have move the content of the demo from the gh-pages branch into a new html file in the demo page. So now when you serve the component with polymer serve you will see the DEMO link and you will see examples.

@jhuesos 

Yeah, I don't use the Polymer cli tooling. I believe that tooling has a way to push the demo folder in master to a gh-pages branch for online demonstration and documentation purposes. So you would still have the two branches in the repo.

I'm certainly open to following the "polymer way" on the matter. If you contribute to documentation, that's enough for me to add you as a collaborator access member to the project.

**Comment by jhuesos** [comment]
How did you generate the content of the branch in gh-pages? Manually or with some tool?

The documentation in polymer is all generated from the source code. In case you haven't try it your self, install polymer-cli and do `polymer serve -o` from the root folder of the project.

I will investigate how to generate a static site from the code.

**Comment by tachyon1337** [comment]
> How did you generate the content of the branch in gh-pages? Manually or with some tool?

Manually, from the command line using standard git commands

I don't use the polymer cli tool b/c it changes, doesn't support jsdoc for documentation(or at least, it didn't used to), creates projects that relies on web components to do things that i don't think should be handled in the DOM layer(like routing, services, etc). Plus I have wrote around 7/8 starter projects that are quite a bit more more sophisticated that I use for my prototype starting points(depending on the project).

[https://ellipticaljs.github.io/google-design/](https://ellipticaljs.github.io/google-design/)
[http://ellipticaljs.github.io/mobile-friendly-prototype/](http://ellipticaljs.github.io/mobile-friendly-prototype/)
[http://ellipticaljs.github.io/mobile-first-dashboard/](http://ellipticaljs.github.io/mobile-first-dashboard/)

And I have my own gulp scaffolding tool that I wrote.

However, I do have a documentation problem when it comes to web components. I generally don't doc them. So I am open to incorporating additional tooling to aid in that endeavor. Polymer 2 looks to be becoming more stabilized, so it might be time conform more to the "polymer way."

**Comment by jhuesos** [comment]
- I have finished the documentation.
- I added polymer-cli to the project and a npm script to start local server: `npm run serve`, following polymer-cli naming convention.

Please review. I will investigate how to generate a static site so you can link it as demo/doc page.

**Comment by tachyon1337** [comment]
@jhuesos 

great! will look over..

**Comment by jhuesos** [comment]
By the way, I didn't bumped the version number. Which version should I give it? Are you following Semver?

**Comment by jhuesos** [comment]
And I found a way to publish the documentation, from the Polymer website:

https://www.polymer-project.org/1.0/docs/tools/reusable-elements#publish

**Comment by tachyon1337** [comment]
> By the way, I didn't bumped the version number. Which version should I give it? Are you following Semver?

@jhuesos 

More or less...minor release bump, 1.2

**Comment by jhuesos** [comment]
Do not merge. I found out that the first demo does not work in IE11. I have been working for hours to find a solution... no so lucky so far. I might need to get rid of the demo-snippet component to make it work.

**Comment by tachyon1337** [comment]
@jhuesos 

I could create a new branch, say, demo-preview, and then merge a new pull request there...fix legacy browser issues before merging to master?

**Comment by jhuesos** [comment]
It have spent literally hours today thinking about how to solve this problem. I think it is a problem with Polymer actually. I even opened a question in stackoverflow: 

http://stackoverflow.com/questions/39915765/element-inside-demo-snippet-is-not-cloned-projected-properly-only-in-ie11

I think it is because IE11 is extremely slow loading the example. The alternative I came up with is to create an example component, something like:

``` html
<local-data-example>
    <paper-autocomplete label="Select State" id="input-local" no-label-float="true">
</paper-autocomplete>
</local-data-example>
```

And inside there, set the source. But the example is not so clear, to be honest. Such a pain in the ass, damn IE11. You have any suggestions?

**Comment by tachyon1337** [comment]
@jhuesos 

I created a temp branch, demo-preview, and merged the pull request into that branch. I can look it at over the weekend RE: IE 11. I have to fire up a VRM windows instance to run IE 11.

**Comment by jhuesos** [comment]
awesome. I am working in a separate branch in parallel in adding A11Y. I made good progress and now the component is way more accessible. I checked with NVDA and it now announces properly the options.

**Comment by tachyon1337** [comment]
@jhuesos 

I consider the IE 11 issue of paper-autocomplete not working within demo-snippet to be a minor one. A warning-style blockquote "demo sample does not support IE 11" would be sufficient IMHO. Then perhaps a link to a separate file, demo-standalone.html(w/o any documentation, just the component example) to verify the thing does actually work in IE 11. In that event, I might suggest putting the sample javascript data wire-up in a separate app.js file for DRY purposes.

**Comment by tachyon1337** [comment]
@jhuesos 

Would vulcanizing the dependencies solve the IE demo-snippet issues?

**Comment by tachyon1337** [comment]
@jhuesos 

i sent a link for you to join this repo as a collaborator. Push your own commits into the demo-preview branch. Then we can do a final merge into master when ready.

Thanx!

**Comment by jhuesos** [comment]
@tachyon1337 to be honest, I agree with you. The component works in IE11, it is just the demo that does not work. Making the demo pages and the example worse and less clear just to make it work in IE11 seems like a waste... But you are the author so this is more a decision for you than for me :D

I am going to try to use vulcanize to see if that helps.

**Comment by tachyon1337** [comment]
@jhuesos 

See if vulcanizing dependencies resolves the issue. If  not, a warning-style blockquote "demo sample does not support IE 11" at the bottom will suffice. 

``` html
<blockquote class="warning">
   <span>NOTE: IE 11 Testing. Demo sample does support legacy IE 11</span>
</blockquote>
```

**Comment by jhuesos** [comment]
@tachyon1337 I added the warning message to the project. I think adding Vulcanize just to make the demo works in IE11 it is not worth it: development will be less convenient (unless we introduce also gulp to have auto-vulcanize feature on change) and in my opinion is not worth it.

Can we merge the branch back to master? Do you have any additional comments? Btw do you mind if I approach you via email so we can discuss a few more topics I have in mind and I would like to contribute?

**Comment by tachyon1337** [comment]
@jhuesos 

I don't care about IE11 and doc/demo. However, I do sort of care about Edge and doc/demo, at least an online version at gh-pages.

Due to a sudden time deadline for a current project, I haven't had a chance to examine the doc/demo updates. I'm fine w/ merging demo-preview into master but I would hold off replacing the current gh-pages w/ the demo folder until closer examination of Polymer demo web component issues w/ MS Edge. 

Regarding additional topic correspondence, I would just use wiki as the tool for that. Roadmaps, suggestions, etc... I also have a facebook-like autocomplete component that I haven't published. I would like to do something w/ that as well.

**Comment by jhuesos** [comment]
Hi @tachyon1337,

I tested in Edge and it works fine. I will double check. About gh-pages, we can wait a bit longer to generate the new version of the pages. The reason I want to merge it back is because I want to release the version since I needed for the project I am working for.

And because all the branches I am creating for fixes are based on that branch, for local development is way more convenient to work being able to serve the demo page and test changes.

I will merge it and publish the new version in bower (aka create git tag).

**Comment by tachyon1337** [comment]
@jhuesos 

Not working in Edge was an assumption on my part. Disregard if its not an issue. 

By all means, go ahead and merge if you're ready to do so.

**Comment by jhuesos** [comment]
@tachyon1337 I talked too fast. the demo page does not work in Edge either... I am trying to come up with a new way of doing the demo, probably creating another component for testing, you have any suggestions? This is really annoying me at this moment, I have spent so much time on this...

**Comment by tachyon1337** [comment]
@jhuesos 

Does vulcanizing dependencies fix the issue? If so, then vulcanize what gets pushed to gh-pages, ...live w/ it not working in Edge/IE in the local version.

**Comment by jhuesos** [comment]
Apparently vulcanize does not support element projects. I have been trying to make it work, changing the paths etc, and I could get something functional but it didn't help. But I have never tried to do this. Have you?

**Comment by tachyon1337** [comment]
@jhuesos 

No...but I'm only concerned w/ Edge working online at gh-pages, not local demo. It shouldn't hold up branch merge...it just means holding off on replacing gh-pages w/ local demo for the moment.

**Pull request merged**
